In [2]:
import tensorflow as tf
from tensorflow.keras.datasets import imdb
from tensorflow.keras.preprocessing.sequence import pad_sequences
from sklearn.metrics import precision_score, recall_score, f1_score, confusion_matrix, accuracy_score

# Hyperparameters
vocab_size=10000
embedding_dim=100
hidden_dim=100
num_of_RNN_layers=1
batch_size=64
learning_rate=0.001
optimizer="adam"
loss="binary_crossentropy"
epochs=10
max_seq_length=256

# Load dataset
(x_train, y_train), (x_test, y_test) = imdb.load_data(num_words=vocab_size)

# Pad/truncate
x_train = pad_sequences(x_train, maxlen=max_seq_length, padding='post', truncating='post')
x_test = pad_sequences(x_test, maxlen=max_seq_length, padding='post', truncating='post')

17464789/17464789 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step


# Vanilla RNN

In [11]:
model_1=tf.keras.Sequential([
    tf.keras.layers.Input(shape=(256,)),
    tf.keras.layers.Embedding(input_dim=10000, output_dim=100),
    tf.keras.layers.SimpleRNN(128),
    tf.keras.layers.Dense(1, activation="sigmoid")
])

model_1.compile(
    loss="binary_crossentropy",
    optimizer=tf.keras.optimizers.Adam(learning_rate=0.001),
    metrics=["accuracy",
             tf.keras.metrics.Precision(name="precision"),
             tf.keras.metrics.Recall(name="recall")]
)

model_1.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)         │ (None, 256, 100)       │     1,000,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn (SimpleRNN)          │ (None, 128)            │        29,312 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │           129 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,029,441 (3.93 MB)

 Trainable params: 1,029,441 (3.93 MB)

 Non-trainable params: 0 (0.00 B)

In [12]:
history_rnn = model_1.fit(
    x_train, y_train,
    epochs=epochs,
    batch_size=batch_size,
    validation_split=0.2
)

Epoch 1/10
313/313 ━━━━━━━━━━━━━━━━━━━━ 13s 31ms/step - accuracy: 0.4976 - loss: 0.6993 - precision: 0.5020 - recall: 0.5103 - val_accuracy: 0.4938 - val_loss: 0.6969 - val_precision: 0.4938 - val_recall: 1.0000
Epoch 2/10
313/313 ━━━━━━━━━━━━━━━━━━━━ 7s 24ms/step - accuracy: 0.5009 - loss: 0.6975 - precision: 0.4945 - recall: 0.4804 - val_accuracy: 0.4938 - val_loss: 0.6981 - val_precision: 0.4938 - val_recall: 1.0000
Epoch 3/10
313/313 ━━━━━━━━━━━━━━━━━━━━ 7s 24ms/step - accuracy: 0.5185 - loss: 0.6927 - precision: 0.5171 - recall: 0.6665 - val_accuracy: 0.4936 - val_loss: 0.6952 - val_precision: 0.4936 - val_recall: 0.9907
Epoch 4/10
313/313 ━━━━━━━━━━━━━━━━━━━━ 8s 24ms/step - accuracy: 0.5370 - loss: 0.6848 - precision: 0.5396 - recall: 0.5247 - val_accuracy: 0.4994 - val_loss: 0.6983 - val_precision: 0.4963 - val_recall: 0.9247
Epoch 5/10
313/313 ━━━━━━━━━━━━━━━━━━━━ 7s 23ms/step - accuracy: 0.5607 - loss: 0.6631 - precision: 0.5633 - recall: 0.5341 - val_accuracy: 0.5066 - val_lo

# LSTM

In [3]:
model_2=tf.keras.Sequential([
    tf.keras.layers.Input(shape=(256,)),
    tf.keras.layers.Embedding(input_dim=10000, output_dim=100),
    tf.keras.layers.LSTM(128),
    tf.keras.layers.Dense(1, activation="sigmoid")
])

model_2.compile(
    loss='binary_crossentropy',
    optimizer=tf.keras.optimizers.Adam(learning_rate=0.001),
    metrics=['accuracy',
             tf.keras.metrics.Precision(name="precision"),
             tf.keras.metrics.Recall(name="recall")]
)

model_2.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (None, 256, 100)       │     1,000,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ (None, 128)            │       117,248 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 1)              │           129 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,117,377 (4.26 MB)

 Trainable params: 1,117,377 (4.26 MB)

 Non-trainable params: 0 (0.00 B)

In [4]:
history_lstm = model_2.fit(
    x_train, y_train,
    epochs=epochs,
    batch_size=batch_size,
    validation_split=0.2
)

Epoch 1/10
313/313 ━━━━━━━━━━━━━━━━━━━━ 11s 18ms/step - accuracy: 0.5118 - loss: 0.6933 - precision: 0.5122 - recall: 0.5634 - val_accuracy: 0.5210 - val_loss: 0.6910 - val_precision: 0.5083 - val_recall: 0.9226
Epoch 2/10
313/313 ━━━━━━━━━━━━━━━━━━━━ 5s 16ms/step - accuracy: 0.5767 - loss: 0.6696 - precision: 0.5915 - recall: 0.5286 - val_accuracy: 0.5288 - val_loss: 0.6853 - val_precision: 0.6160 - val_recall: 0.1215
Epoch 3/10
313/313 ━━━━━━━━━━━━━━━━━━━━ 6s 18ms/step - accuracy: 0.5969 - loss: 0.6220 - precision: 0.6170 - recall: 0.5573 - val_accuracy: 0.5734 - val_loss: 0.7046 - val_precision: 0.6582 - val_recall: 0.2831
Epoch 4/10
313/313 ━━━━━━━━━━━━━━━━━━━━ 5s 16ms/step - accuracy: 0.5902 - loss: 0.6245 - precision: 0.5979 - recall: 0.5642 - val_accuracy: 0.5666 - val_loss: 0.6900 - val_precision: 0.6458 - val_recall: 0.2710
Epoch 5/10
313/313 ━━━━━━━━━━━━━━━━━━━━ 6s 18ms/step - accuracy: 0.6973 - loss: 0.5300 - precision: 0.6941 - recall: 0.7214 - val_accuracy: 0.7406 - val_lo

# GRU

In [7]:
model_3=tf.keras.Sequential([
    tf.keras.layers.Input(shape=(256,)),
    tf.keras.layers.Embedding(input_dim=10000, output_dim=100),
    tf.keras.layers.GRU(128),
    tf.keras.layers.Dense(1, activation="sigmoid")
])

model_3.compile(
    loss='binary_crossentropy',
    optimizer=tf.keras.optimizers.Adam(learning_rate=0.001),
    metrics=['accuracy',
             tf.keras.metrics.Precision(name="precision"),
             tf.keras.metrics.Recall(name="recall")]
)

model_3.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ (None, 256, 100)       │     1,000,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ gru (GRU)                       │ (None, 128)            │        88,320 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │           129 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,088,449 (4.15 MB)

 Trainable params: 1,088,449 (4.15 MB)

 Non-trainable params: 0 (0.00 B)

In [8]:
history_gru = model_3.fit(
    x_train, y_train,
    epochs=epochs,
    batch_size=batch_size,
    validation_split=0.2
)

Epoch 1/10
313/313 ━━━━━━━━━━━━━━━━━━━━ 8s 20ms/step - accuracy: 0.4987 - loss: 0.6940 - precision: 0.5033 - recall: 0.5970 - val_accuracy: 0.5154 - val_loss: 0.6923 - val_precision: 0.5227 - val_recall: 0.2143
Epoch 2/10
313/313 ━━━━━━━━━━━━━━━━━━━━ 5s 15ms/step - accuracy: 0.5712 - loss: 0.6737 - precision: 0.5971 - recall: 0.4816 - val_accuracy: 0.5274 - val_loss: 0.6952 - val_precision: 0.5664 - val_recall: 0.1831
Epoch 3/10
313/313 ━━━━━━━━━━━━━━━━━━━━ 5s 16ms/step - accuracy: 0.6135 - loss: 0.5931 - precision: 0.6138 - recall: 0.6289 - val_accuracy: 0.6234 - val_loss: 0.6723 - val_precision: 0.5765 - val_recall: 0.8943
Epoch 4/10
313/313 ━━━━━━━━━━━━━━━━━━━━ 5s 17ms/step - accuracy: 0.6992 - loss: 0.5118 - precision: 0.7145 - recall: 0.6688 - val_accuracy: 0.6298 - val_loss: 0.6941 - val_precision: 0.6200 - val_recall: 0.6468
Epoch 5/10
313/313 ━━━━━━━━━━━━━━━━━━━━ 5s 15ms/step - accuracy: 0.7994 - loss: 0.4364 - precision: 0.7780 - recall: 0.8392 - val_accuracy: 0.8030 - val_los

In [15]:
def evaluate_model(model, x_test, y_test):
    y_prob = model.predict(x_test)
    y_pred = (y_prob > 0.5).astype("int32")

    acc = accuracy_score(y_test, y_pred)
    prec = precision_score(y_test, y_pred)
    rec = recall_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred)
    cm = confusion_matrix(y_test, y_pred)

    return acc, prec, rec, f1, cm

In [16]:
rnn_results = evaluate_model(model_1, x_test, y_test)
lstm_results = evaluate_model(model_2, x_test, y_test)
gru_results = evaluate_model(model_3, x_test, y_test)

print("RNN Results:")
print("Accuracy:", rnn_results[0])
print("Precision:", rnn_results[1])
print("Recall:", rnn_results[2])
print("F1-score:", rnn_results[3])
print("Confusion Matrix:\n", rnn_results[4])

print("\nLSTM Results:")
print("Accuracy:", lstm_results[0])
print("Precision:", lstm_results[1])
print("Recall:", lstm_results[2])
print("F1-score:", lstm_results[3])
print("Confusion Matrix:\n", lstm_results[4])

print("\nGRU Results:")
print("Accuracy:", gru_results[0])
print("Precision:", gru_results[1])
print("Recall:", gru_results[2])
print("F1-score:", gru_results[3])
print("Confusion Matrix:\n", gru_results[4])

782/782 ━━━━━━━━━━━━━━━━━━━━ 6s 7ms/step
782/782 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step
782/782 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step
RNN Results:
Accuracy: 0.50044
Precision: 0.5002581069031864
Recall: 0.8528
F1-score: 0.6306013191753675
Confusion Matrix:
 [[ 1851 10649]
 [ 1840 10660]]

LSTM Results:
Accuracy: 0.82212
Precision: 0.8121559810838049
Recall: 0.83808
F1-score: 0.8249143667073506
Confusion Matrix:
 [[10077  2423]
 [ 2024 10476]]

GRU Results:
Accuracy: 0.8156
Precision: 0.8315683308119012
Recall: 0.79152
F1-score: 0.8110500860726289
Confusion Matrix:
 [[10496  2004]
 [ 2606  9894]]


# Եզրակացություն

Ըստ ստացված արդյունքների տեսնում ենք , որ ամենալավ արդյունքները ցույց է տվել LSTM-ը։